apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-http
spec:
  replicas: 1
  template:
     spec:
      securityContext:
        runAsUser: 10105
        runAsGroup: 10105
        fsGroup: 10105