apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
images:
- name: registry.t-d-h.net/golang-http
  newTag: "v1"