apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-http
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: registry.t-d-h.net/golang-http:v1
        command:
        - ./main
        resources:
          limits: 
            cpu: 2
            memory: 1Gi
        ports:
        - containerPort: 8090
          name: http