apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: golang-http
resources:
- deployment.yaml
- service.yaml
images:
- name: registry.t-d-h.net/golang-http
  newTag: "v1"
